repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy
    pass_filenames: false
    additional_dependencies:
    - asyncssh
    - git+https://github.com/iiasa/ixmp.git@main
    - importlib_resources
    - matplotlib
    - pandas-stubs
    - pytest
    - Sphinx
    - types-PyYAML
    - types-requests
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.1
  hooks:
  - id: ruff
  - id: ruff-format
    args: [ --check ]

# GitHub Actions workflows
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
    name: Validate GitHub Actions workflow YAML
    files: '.github/workflows/.*\.ya?ml'
- repo: local
  hooks:
  - id: validate-github-actions
    name: Validate GitHub Actions workflow schema
    language: rust
    entry: action-validator
    additional_dependencies: [ cli:action-validator:0.6.0 ]
    files: '.github/workflows/.*\.ya?ml'
